# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules/alert.rules'
  - 'rules/ssl_expiry.rules'
  - 'rules/windows.rules' 
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
        - localhost:9090
        - cadvisor:8080
        - node-exporter:9100

  - job_name: 'ICMP'
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    ec2_sd_configs:
        - region: us-east-1
          access_key: <aws-access-key>
          secret_key: <aws-secret-key>
    relabel_configs:
      - source_labels: ['__meta_ec2_instance_state']
        regex: 'running'
        action: 'keep'
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        regex: '(.*):\d+'
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"

  - job_name: 'HTTP'
    metrics_path: /probe
    file_sd_configs:
      - files:
        - 'targets/http_2xx.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance

  - job_name: 'AWS-Windows'
    ec2_sd_configs:
      - region: us-east-1
        access_key: <aws-access-key>
        secret_key: <aws-secret-key>
        port: 9182
        refresh_interval: 1m
    relabel_configs:
      - source_labels: ['__meta_ec2_instance_state']
        regex: 'running'
        action: 'keep'
      - source_labels: ['__meta_ec2_platform']
        regex: 'windows'
        action: 'keep'
      - source_labels: ['__meta_ec2_tag_Name']
        target_label: name
      - source_labels: ['__meta_ec2_tag_NotifyTeam']
        target_label: NotifyTeam
      - source_labels: [__param_target]
        regex: '(.*):\d+'
        target_label: instance
